from __future__ import annotations

"""Named calibration constants for Discovery heuristics.

These are intentionally separated from the causal-logic helpers so domain tuning can
happen in one place. The constants below are *ranking and workflow heuristics*, not
causal estimands. Changing them can affect prioritization and proposal routing even
when the underlying evidence is unchanged.
"""

# Confounder screening / adjustment
CONFOUNDER_MIN_ABS_CORR = 0.16
CONFOUNDER_TEMPORAL_NAME_BONUS = 0.08
RAW_STRENGTH_DELTA_WEIGHT = 0.35
CONFOUNDING_RISK_NO_CONTROLS = 0.10
CONFOUNDING_RISK_ATTENUATION_WEIGHT = 0.55
CONFOUNDING_RISK_ZX_WEIGHT = 0.25
CONFOUNDING_RISK_ZY_WEIGHT = 0.20
MAX_SELECTED_CONFOUNDERS = 3
MAX_CONFOUNDER_HINTS = 5

# Testability scoring
TESTABILITY_COV_WEIGHT = 0.22
TESTABILITY_TIMESTAMP_WEIGHT = 0.16
TESTABILITY_ACTION_DEFINED_WEIGHT = 0.16
TESTABILITY_WINDOW_WEIGHT = 0.16
TESTABILITY_COV_SUPPORT_WEIGHT = 0.12
TESTABILITY_ACTIONABILITY_WEIGHT = 0.18
TESTABILITY_GOOD_TS_COVERAGE = 0.70
TESTABILITY_MID_TS_SCORE = 0.70
TESTABILITY_ACTION_DEFINED_HIGH_UNIQ = 8
TESTABILITY_ACTION_DEFINED_MID_UNIQ = 5
TESTABILITY_ACTION_DEFINED_MID_SCORE = 0.70
TESTABILITY_ACTION_DEFINED_LOW_SCORE = 0.35
TESTABILITY_COV_SUPPORT_DENOM = 6.0
TESTABILITY_COVARIATE_MIN_COVERAGE = 0.50

# Actionability priors
ACTIONABILITY_HIGH = 0.95
ACTIONABILITY_BASE = 0.65
ACTIONABILITY_LOW = 0.35
ACTIONABILITY_LOW_NAME_TOKENS = ("score", "index", "latent", "outcome_prev", "target_prev")

# Safety / multi-outcome blending
BENEFIT_RELATION_WEIGHT = 0.65
BENEFIT_CORR_WEIGHT = 0.35
BENEFIT_CORR_SCALE = 0.30
HARM_SCALE = 0.40
HARM_DEFAULT = 0.05
UNCERTAINTY_INSTABILITY_WEIGHT = 0.65
UNCERTAINTY_LEAKAGE_WEIGHT = 0.35
SAFETY_NET_BENEFIT_WEIGHT = 0.55
SAFETY_NET_HARM_WEIGHT = 0.25
SAFETY_NET_UNCERTAINTY_WEIGHT = 0.20
INSTABILITY_DEFAULT = 0.75

# Structural risk scoring
STRUCT_RISK_LEAKAGE_WEIGHT = 0.45
STRUCT_RISK_LEAKAGE_CAP = 0.60
STRUCT_RISK_DAG_REVIEW = 0.18
STRUCT_RISK_DAG_UNKNOWN = 0.08
STRUCT_RISK_REGIME_WEIGHT = 0.20
STRUCT_RISK_REGIME_CAP = 0.20
STRUCT_RISK_SENSITIVE_DOMAIN = 0.35
STRUCT_RISK_HARD_EXCLUSION = 0.60
STRUCT_RISK_OTHER_FLAG = 0.08

# Conditional-adjustment heuristics
CI_MIN_SURVIVAL_ABS_CORR = 0.08
CI_MIN_SURVIVAL_ABS_DELTA = 0.10
CI_RELATIVE_SURVIVAL_FRACTION = 0.45
CI_SIGNAL_DENOM_MIN = 0.16

# Proposal scoring before adjustment
SIGNAL_CORR_WEIGHT = 0.65
SIGNAL_DELTA_WEIGHT = 0.35
SIGNAL_CORR_SCALE = 0.35
SIGNAL_DELTA_SCALE = 1.0
DIRECTION_MATCH_SCORE = 1.0
DIRECTION_MISMATCH_SCORE = 0.45
MECHANISM_NEAR_LAG_SCORE = 0.85
MECHANISM_MID_LAG_SCORE = 0.70
MECHANISM_FAR_LAG_SCORE = 0.45
MECHANISM_NEAR_LAG_MAX = 3
MECHANISM_MID_LAG_MAX = 7
INTERVENTION_SIGNAL_WEIGHT = 0.65
INTERVENTION_CORR_WEIGHT = 0.35
DOWNSIDE_INTERVENTION_WEIGHT = 0.70
DOWNSIDE_TESTABILITY_WEIGHT = 0.30
READINESS_TESTABILITY_WEIGHT = 0.60
READINESS_STABILITY_WEIGHT = 0.25
READINESS_WINDOWS_WEIGHT = 0.15
READINESS_WINDOWS_GOOD_SCORE = 1.0
READINESS_WINDOWS_PARTIAL_SCORE = 0.5

# Adjustment blend / persistence / priority
ADJUSTMENT_BLEND_CAUSAL_PRIOR = 0.42
ADJUSTMENT_BLEND_ADJUSTED_SIGNAL = 0.58
ADJUSTMENT_BLEND_INTERVENTION_PRIOR = 0.50
ADJUSTMENT_BLEND_INTERVENTION_ADJUSTED = 0.50
ADJUSTMENT_LOW_ABS_CORR = 0.05
ADJUSTMENT_HIGH_ABS_CORR = 0.08
ADJUSTMENT_LOW_RELATIVE_CORR = 0.55
ADJUSTMENT_HIGH_RELATIVE_CORR = 0.60
CAUSAL_BLEND_BASE = 0.72
CAUSAL_BLEND_CI = 0.16
CAUSAL_BLEND_PARENT = 0.12
CAUSAL_CONF_RISK_PENALTY = 0.24
DOWNSIDE_CONF_RISK_PENALTY = 0.12
READINESS_SUPPORT_BLEND_BASE = 0.82
READINESS_SUPPORT_BLEND_SUPPORT = 0.18
READINESS_SUPPORT_DENOM_MIN = 20.0
PERSISTENCE_ATTENUATION_WEIGHT = 0.55
PERSISTENCE_EFFECT_WEIGHT = 0.45

PRIORITY_DOWNSIDE_WEIGHT = 0.26
PRIORITY_CAUSAL_WEIGHT = 0.24
PRIORITY_TESTABILITY_WEIGHT = 0.13
PRIORITY_STRUCTURAL_SAFETY_WEIGHT = 0.10
PRIORITY_PERSISTENCE_WEIGHT = 0.11
PRIORITY_EFFECT_WEIGHT = 0.08
PRIORITY_PARENT_WEIGHT = 0.05

# Feedback / regime blend safety rails
REGIME_READINESS_PENALTY = 0.15
REGIME_ALIGNMENT_BONUS_THRESHOLD = 0.70
VALIDATION_READINESS_NOOP_BLEND = 0.60

# Risk flag and precheck thresholds
STABILITY_GOOD_THRESHOLD = 0.50
STABILITY_BAD_THRESHOLD = 0.35
LEAKAGE_VERY_HIGH_LAG0 = 0.95
LEAKAGE_FUTURE_MARGIN = 0.08
HARM_REVIEW_THRESHOLD = 0.55
HARM_BLOCK_THRESHOLD = 0.60
UNCERTAINTY_REVIEW_THRESHOLD = 0.60
UNCERTAINTY_BLOCK_THRESHOLD = 0.70
REGIME_ALIGNMENT_GOOD_THRESHOLD = 0.65
STRUCTURAL_REVIEW_THRESHOLD = 0.75
LEAKAGE_REVIEW_THRESHOLD = 0.60

# Keep / track thresholds
KEEP_MIN_DOWNSIDE = 0.28
KEEP_MIN_TESTABILITY_FLOOR = 0.34
KEEP_MAX_STRUCTURAL_RISK = 0.88
WEAK_SIGNAL_PRIORITY_MAX = 0.30
VERY_LOW_CAUSAL_MAX = 0.18
TRACK_HIGH_PRIORITY_FLOOR = 0.56
TRACK_HIGH_PLAUSIBILITY = 0.38
TRACK_HIGH_DOWNSIDE = 0.24
TRACK_HIGH_STRUCTURAL_MAX = 0.82
TRACK_HIGH_CONF_RISK_MAX = 0.55
TRACK_HIGH_CI = 0.22
TRACK_HIGH_PARENT = 0.28
TRACK_EXPLORATORY_PLAUSIBILITY = 0.24
TRACK_EXPLORATORY_DOWNSIDE = 0.14
TRACK_EXPLORATORY_STRUCTURAL_MAX = 0.90
TRACK_WEAK_PLAUSIBILITY = 0.14
TRACK_WEAK_DOWNSIDE = 0.10
DROP_HIGH_STRUCTURAL = 0.92

# Hypothesis contextualization
CONTEXT_READINESS_DELTA = 0.05
CONTEXT_READINESS_FLOOR = 0.18
CONTEXT_PRIORITY_BONUS = 0.02
CONTEXT_PRIORITY_CAP = 0.99
