from __future__ import annotations

"""Central status constants for the conservative SCM ID layer."""

from typing import Dict

ID_ALGORITHM_VERSION = 59
ID_ALGORITHM_STATUS = "limited_scaffold_with_recursive_id_step29_authority_separation_formula_ast_step42_ast_runtime_step43_q_input_recursion_step44_q_factor_general_recursion_step45_carried_q_context_step51_carried_q_ast_step52_exact_fail_branch_hedge_step46_and_canonical_proof_trace_step47_completeness_matrix_step48_full_id_public_facade_step49_canonical_control_flow_step50_carried_q_context_step51_carried_q_ast_step52_operational_carried_q_ast_step53_ast_normalizer_step54_canonical_formula_authority_step55_canonical_id7_carried_q_formula_step56_idc_normalization_step57_full_id_readiness_matrix_step58_canonical_id4_formula_authority_step59_contextual_id7_step60_failure_certificates_step61_idc_pruning_step62_agentic_full_id_adapter_step63_symbolic_ast_evaluator_step64_idc_fraction_numeric_step65_chain_frontdoor_and_q_factor_numeric_step66_parallel_frontdoor_set_step67_failure_authority_separation_step68_do_proof_metadata_step73_canonical_templates_step74_arbitrary_id7_carried_q_marginalization_step75_oracle_parity_fuzz_step79_downstream_confounded_chain_step79_audited_fuzz_closure_step80_full_id_promotion_gate_step82_failure_certificate_coverage_step83_subforest_hedge_step84_recursive_authority_coverage_step85_recursive_trace_authority_step86_scoped_pearl_promotion_step87_scope_manifest_step88_release_manifest_step89_runtime_attestation_step90_full_recursive_kernel_step91_recursive_oracle_expansion_step92_global_full_id_promotion_dry_run_step93_controlled_global_full_id_flip_step94_global_pearl_veto_runtime_release_step95_global_pearl_no_overclaim_adversarial_suite_step96_final_pearl_readiness_report_step97_math_hypothesis_dialogue_loop_step99"

ID_CAPABILITY_FLAGS: Dict[str, object] = {
    "id_algorithm_version": ID_ALGORITHM_VERSION,
    "id_algorithm_status": ID_ALGORITHM_STATUS,
    "full_recursive_id_implemented": 1,
    "full_id_claim_allowed": 1,
    "id_full_arbitrary_id7_carried_q_marginalization_step75_implemented": 1,
    "id_full_oracle_parity_fuzz_step76_implemented": 1,
    "id_full_oracle_parity_fuzz_step79_implemented": 1,
    "id_full_downstream_confounded_chain_id7_step79_implemented": 1,
    "id_full_audited_fuzz_closure_step80_implemented": 1,
    "id_full_promotion_gate_step82_implemented": 1,
    "id_full_failure_certificate_coverage_step83_implemented": 1,
    "id_full_subforest_hedge_certificates_step84_implemented": 1,
    "id_full_recursive_authority_coverage_step85_implemented": 1,
    "id_full_recursive_trace_authority_step86_implemented": 1,
    "id_scoped_pearl_promotion_step87_implemented": 1,
    "id_scoped_pearl_scope_manifest_step88_implemented": 1,
    "id_scoped_pearl_release_manifest_step89_implemented": 1,
    "id_scoped_pearl_veto_runtime_attestation_step90_implemented": 1,
    "id_full_recursive_kernel_step91_implemented": 1,
    "id_full_recursive_oracle_expansion_step92_implemented": 1,
    "id_global_full_id_promotion_dry_run_step93_implemented": 1,
    "id_global_full_id_controlled_flip_step94_implemented": 1,
    "id_global_pearl_veto_runtime_release_step95_implemented": 1,
    "id_global_pearl_no_overclaim_adversarial_suite_step96_implemented": 1,
    "id_global_pearl_no_overclaim_adversarial_suite_version": "veto_pearl_global_no_overclaim_adversarial_suite_v1_step96",
    "id_final_pearl_readiness_report_step97_implemented": 1,
    "id_final_pearl_readiness_report_version": "id_final_pearl_readiness_report_v1_step97",
    "math_hypothesis_dialogue_loop_step99_implemented": 1,
    "math_hypothesis_dialogue_loop_version": "math_hypothesis_dialogue_loop_v1_step99",
    "math_hypothesis_loop_readiness_version": "math_hypothesis_dialogue_loop_product_readiness_v1_step99",
    "diagnostic_authority_separation_step41_implemented": 1,
    "full_recursive_id_step2_implemented": 1,
    "full_recursive_id_step3_implemented": 1,
    "full_recursive_id_step4_implemented": 1,
    "general_q_input_recursion_step44_implemented": 1,
    "full_recursive_id_step5_partial_implemented": 1,
    "q_factor_general_recursion_step45_implemented": 1,
    "exact_fail_branch_hedge_step46_implemented": 1,
    "canonical_id_proof_trace_step47_implemented": 1,
    "id_completeness_matrix_step48_implemented": 1,
    "id_full_public_facade_step49_implemented": 1,
    "id_full_canonical_control_flow_step50_implemented": 1,
    "id_full_carried_q_context_step51_implemented": 1,
    "id_full_carried_q_ast_step52_implemented": 1,
    "id_full_operational_carried_q_ast_step53_implemented": 1,
    "id_full_formula_ast_normalizer_step54_implemented": 1,
    "id_full_canonical_formula_authority_step55_implemented": 1,
    "id_full_canonical_id7_carried_q_formula_step56_implemented": 1,
    "id_full_idc_normalization_step57_implemented": 1,
    "id_full_readiness_matrix_step58_implemented": 1,
    "id_full_canonical_id4_formula_authority_step59_implemented": 1,
    "id_full_contextual_id7_carried_q_formula_step60_implemented": 1,
    "id_full_failure_certificates_step61_implemented": 1,
    "id_full_idc_pruning_step62_implemented": 1,
    "id_full_agentic_adapter_step63_implemented": 1,
    "id_full_symbolic_ast_evaluator_step64_implemented": 1,
    "id_full_idc_fraction_numeric_step65_implemented": 1,
    "id_full_chain_frontdoor_id7_step66_implemented": 1,
    "id_full_q_factor_numeric_step66_implemented": 1,
    "id_full_parallel_frontdoor_set_id7_step67_implemented": 1,
    "id_full_failure_authority_separation_step68_implemented": 1,
    "id_full_do_proof_metadata_step73_implemented": 1,
    "id_full_do_canonical_proof_templates_step74_implemented": 1,
    "id_full_arbitrary_id7_carried_q_marginalization_step75_level": "recursive ID-7 carries Q[S_prime] through ancestor reductions by preserving source terms and marginalizing removed source variables before observed-DAG/Q-factor branches; one non-frontdoor readiness case is green, no arbitrary Full-ID claim yet",
    "id_full_oracle_parity_fuzz_step76_level": "curated oracle parity matrix plus deterministic ADMG no-overclaim fuzz guard; originally tracked delegated recursive ID-7 formula gaps without enabling Full-ID/Pearl-complete claims",
    "id_full_oracle_parity_fuzz_step79_level": "curated oracle parity matrix plus deterministic ADMG no-overclaim fuzz guard now verifies the Step-79 downstream-confounded chain gap is closed without enabling Full-ID/Pearl-complete claims",
    "id_full_downstream_confounded_chain_id7_step79_level": "strict owned canonical ID-7 carried-Q formula for X->A->B->Y with X<->B and no extra nodes or edges; closes one delegated recursive formula gap while keeping full_recursive_id_implemented=0",
    "id_full_audited_fuzz_closure_step80_level": "strict finite four-node recursive ID-7 fuzz closure authority for six previously raw delegated formulas; audited authority only, not arbitrary Full-ID/Pearl-complete authority",
    "id_full_promotion_gate_step82_level": "full_id_and_pearl_promotion_gate_requires_full_recursive_id_flags_readiness_oracle_fuzz_failure_certificate_coverage_and_full_recursive_formula_authority; current backend stays blocked",
    "id_full_failure_certificate_coverage_step83_level": "dedicated failure-certificate coverage matrix audits readiness/oracle/fuzz nonidentified rows and exposes technical-pending rows as promotion blockers",
    "id_full_subforest_hedge_certificates_step84_level": "audited finite subforest hedge search closes the current fuzz_step76_045 and fuzz_step76_054 pending ID-5 failures with formal hedge certificates; still no Full-ID/Pearl claim",
    "id_full_recursive_trace_authority_step86_level": "scoped recursive ID-1_to_ID-7 trace certificates cover every current public identified formula row as full_recursive_id_trace_formula_authority_step86; global full_recursive_id_implemented and full_id_claim_allowed remain 0",
    "id_scoped_pearl_promotion_step87_level": "scope-bound Pearl-veto release gate is green for the audited public readiness/oracle/fuzz surface using Step84 failure coverage plus Step86 recursive trace formula authority, while global arbitrary Full-ID flags remain 0",
    "id_scoped_pearl_scope_manifest_step88_level": "hash-bound scoped Pearl manifest binds the Step87 release gate to exact readiness/oracle/fuzz/failure/recursive-authority matrix versions and counts; runtime blocks stale or tampered scoped Pearl cards",
    "id_scoped_pearl_release_manifest_step89_level": "release-bound scoped Pearl manifest binds Step88 manifest digest and code file hashes for the scoped Pearl/veto authority path; runtime blocks stale cards built against drifted code or matrices",
    "id_scoped_pearl_veto_runtime_attestation_step90_level": "runtime-bound scoped Pearl veto attestation binds HARD_BLOCK/REVIEW decision, top path, Step88 scope manifest digest, Step89 release digest, recursive trace authority and global Full-ID-off flags into a sha256 envelope; no global Pearl-complete claim",
    "id_full_recursive_kernel_step91_level": "first-class recursive-ID kernel backend matrix exposes ID-1_to_ID-7 traces, district decomposition, carried-Q recursion, observed-DAG set queries, and formal hedge certificate paths; global Full-ID claim flag remains blocked",
    "id_full_recursive_oracle_expansion_step92_level": "broad deterministic recursive-ID kernel oracle expansion over curated and stratified five-node ADMG surfaces; all sampled queries must complete with formula AST or formal hedge certificate before global promotion can proceed",
    "id_global_full_id_promotion_dry_run_step93_level": "pre-flip global Full-ID promotion dry-run proves the Step92 promotion gate is blocked only by global flags, simulates the flip in memory, and keeps status flags unchanged",
    "id_global_full_id_controlled_flip_step94_level": "controlled global Full-ID release verifies the Step93 archived pre-flip dry-run, flips full_recursive_id_implemented and full_id_claim_allowed atomically, and requires the live promotion gate to pass",
    "id_global_pearl_veto_runtime_release_step95_level": "Global Pearl-complete veto wording requires causal-veto authority, Step94 controlled Global Full-ID flip evidence, live Full-ID promotion evidence, full recursive formula authority, and a digest-bound runtime attestation over the top veto path and decision",
    "id_global_pearl_no_overclaim_adversarial_suite_step96_level": "adversarial no-overclaim suite requires positive Global Pearl control plus negative blocks for policy-only cards, finite formula spoofing, missing Step94 evidence, stale readiness/oracle/promotion/controlled-flip versions, non-veto decisions, and tampered/replayed attestations",
    "id_final_pearl_readiness_report_step97_level": "final Global Pearl readiness report binds Global Full-ID promotion, Step94 controlled flip, Step95/96 runtime attestation release, and Step96 adversarial no-overclaim suite into one digest-bound evidence report",
    "math_hypothesis_dialogue_loop_step99_level": "bounded LLM-to-math-critic loop that vetoes proof overclaim, recommends lemmas/proof obligations, downgrades famous-open-problem claims, and emits digest-bound dialogue evidence; not an automatic theorem prover",
    "id_full_agentic_adapter_step63_level": "causalgate_causal_core_identification_engine_routes_online_agentic_queries_to_full_id_and_idc_pruning_set_valued_treatments_outcomes_conditions_no_full_id_claim",
    "id_full_symbolic_ast_evaluator_step64_level": "symbolic_evaluator_accepts_normalized_formula_ast_json_and_routes_sum_product_fraction_do_q_factor_hedge_fail_nodes_conservatively_no_full_id_claim",
    "id_full_idc_fraction_numeric_step65_level": "resolved_IDC_fraction_ASTs_route_to_contract_gated_symbolic_numeric_idc_fraction_ratio_conditional_mean_standardization_Q_placeholder_hedge_nodes_remain_blocked_no_full_id_claim",
    "id_full_chain_frontdoor_id7_step66_level": "narrow_two_or_more_mediator_chain_frontdoor_ID7_carried_Q_formula_for_X_to_Z_chain_to_Y_with_X_bidirected_Y_no_arbitrary_ID7_claim",
    "id_full_q_factor_numeric_step66_level": "resolved_Q_factor_ASTs_with_probability_sum_product_do_children_route_to_contract_gated_standardization_bare_or_nested_Q_inputs_remain_blocked_no_full_id_claim",
    "id_full_parallel_frontdoor_set_id7_step67_level": "strict_multi_mediator_parallel_frontdoor_set_ID7_carried_Q_formula_for_X_to_each_Z_and_each_Z_to_Y_with_X_bidirected_Y_no_extra_edges_no_arbitrary_ID7_claim",
    "id_full_downstream_confounded_chain_id7_step79_level_short": "strict_two_mediator_downstream_confounding_ID7_carried_Q_formula_no_arbitrary_ID7_claim",
    "id_full_failure_authority_separation_step68_level": "nonidentified_full_id_outputs_use_id_failure_certificate_step68_as_primary_non_formula_authority_so_readiness_delegate_counts_only_identified_formula_construction_no_full_id_claim",
    "id_full_do_proof_metadata_step73_level": "full_id_attaches_bounded_do_calculus_proof_engine_result_as_audit_metadata_only_no_formula_authority_no_full_id_claim_no_veto_authority",
    "id_full_do_canonical_proof_templates_step74_level": "bounded_do_calculus_proof_engine_uses_audit_only_canonical_zero_effect_backdoor_and_limited_frontdoor_templates_no_formula_authority_no_full_id_claim_no_veto_authority",
    "id_full_public_facade_level": "set_valued_full_id_shaped_api_with_canonical_id_1_to_7_control_flow_owned_formula_authority_ID1_ID2_ID4_ID6_gated_ID7_frontdoor_contextual_IDC_ratio_normalization_and_IDC_pruning_no_full_id_claim",
    "id_full_failure_certificates_step61_level": "standardized_failure_certificate_channel_for_full_id_and_idc_nonidentified_outputs_formal_hedge_when_certified_else_explicit_technical_pending_no_full_id_claim",
    "id_full_idc_pruning_step62_level": "conservative_IDC_condition_pruning_removes_conditions_disconnected_from_outcomes_after_doX_before_ratio_over_identified_joint_no_full_idc_claim",
    "id_full_canonical_control_flow_level": "machine_readable_ID_1_to_ID_7_orchestrator_overlay_before_recursive_expression_delegate",
    "id_full_carried_q_context_level": "explicit_Q_scope_Q_terms_and_projection_metadata_for_ID_7_carried_q_recursion_no_full_id_claim",
    "id_full_carried_q_ast_level": "carried_Q_context_exposes_id_ast_v1_formula_ast_for_ID_7_Q_input_no_full_id_claim",
    "id_full_operational_carried_q_ast_level": "recursive_runtime_accepts_carried_Q_formula_ast_as_operational_Q_input_for_supported_ID_7_base_and_full_district_branches_no_full_id_claim",
    "id_full_formula_ast_normalizer_level": "recursive_ID_expression_payloads_serialize_normalized_id_ast_v1_nodes_for_sum_product_fraction_do_q_factor_hedge_fail_and_step75_marginalized_carried_Q_no_full_id_claim",
    "id_full_canonical_formula_authority_level": "owned_formula_authority_for_canonical_ID_1_ID_2_ID_4_and_ID_6_branches_no_full_id_claim",
    "id_full_canonical_id4_formula_authority_step59_level": "canonical_ID4_district_decomposition_product_with_recursive_canonical_subproblem_formulas_reduces_delegate_authority_no_full_id_claim",
    "id_full_canonical_id7_carried_q_formula_level": "gated_classic_and_contextual_frontdoor_shaped_ID7_carried_Q_formula_with_alpha_renamed_treatment_prime_and_direct_confounding_fail_guard_no_full_id_claim",
    "id_full_idc_normalization_step57_level": "conditional_interventional_distribution_api_identifies_P_Y_given_do_X_Z_as_ratio_over_identified_joint_P_YZ_given_do_X_no_new_full_id_claim",
    "id_full_readiness_matrix_step58_level": "18_case_public_full_id_and_idc_readiness_matrix_covering_canonical_ID6_ID7_frontdoor_Q_factor_hedge_invalid_cycle_multi_set_and_IDC_ratio_cases_no_full_id_claim",
    "id_full_contextual_id7_carried_q_formula_step60_level": "canonical_contextual_frontdoor_joint_outcome_formula_for_P_YC_given_do_X_enables_IDC_joint_authority_no_full_id_claim",
    "formal_hedge_authority_level": "certified_only_from_recursive_id_fail_branch_not_from_standalone_diagnostic",
    "q_factor_general_recursion_level": "standalone_q_factor_module_delegates_strict_subdistrict_q_input_queries_to_recursive_expression_runtime_with_step51_carried_q_context",
    "formal_hedge_certificate_step27_implemented": 1,
    "localized_hedge_certificate_step28_implemented": 1,
    "set_valued_q_input_recursion_step29_implemented": 1,
    "q_input_subdistrict_recursion_step23_implemented": 1,
    "set_valued_recursive_expression_api_step24_implemented": 1,
    "q_input_formula_alpha_renaming_step24_implemented": 1,
    "recursive_id_skeleton_implemented": 1,
    "hedge_detection_level": "ancestral_c_component_witness_diagnostic_strict_roots_with_step84_audited_subforest_fallback",
    "formal_hedge_construction_implemented": 1,
    "formal_hedge_candidate_diagnostic_implemented": 1,
    "d_separation_diagnostic_level": "latent_expanded_admg_paths",
    "frontdoor_diagnostic_level": "limited_pearl_conditions_with_dsep",
    "observed_dag_factorization_level": "explicit_truncated_factorization_formula",
    "c_component_diagnostic_level": "ancestral_district_decomposition_with_q_placeholders",
    "recursive_id_diagnostic_level": "ancestor_reduction_w_step_observed_dag_base_case_district_decomposition_q_factor_step2_q_input_subdistrict_step3_formal_hedge_candidate",
    "recursive_id_expression_level": "set_valued_recursive_expression_step29_multi_intervention_q_input_q_factor_step4_localized_formal_hedge_certificate_ast_runtime_step43_structured_q_input_recursion_step44_q_factor_general_recursion_step45_carried_q_context_step51_carried_q_ast_step52_operational_carried_q_ast_step53_exact_fail_branch_hedge_step46",
    "c_factor_decomposition_level": "ancestral_district_product_with_q_placeholders",
    "symbolic_formula_layer_implemented": 1,
    "formula_ast_step42_implemented": 1,
    "formula_ast_runtime_step43_implemented": 1,
    "formula_ast_runtime_level": "recursive_expression_builds_ast_internally_for_supported_branches_and_uses_carried_q_input_subproblem_ast_operationally_with_parser_fallback_then_normalizes_AST_shape_step54",
    "formula_ast_version": "id_ast_v1",
    "symbolic_formula_level": "structured_json_terms_with_id_ast_v1_for_supported_limited_estimands_carried_Q_contexts_and_unresolved_c_factors",
    "id_proof_trace_implemented": 1,
    "id_proof_trace_level": "machine_readable_route_steps_formula_tree_and_canonical_id_1_to_7_overlay_no_new_authority",
    "canonical_id_proof_trace_level": "maps_recursive_runtime_trace_to_ID_1_no_intervention_ID_2_ancestor_reduction_ID_3_w_step_ID_4_district_decomposition_ID_5_fail_hedge_ID_6_q_factor_ID_7_q_input_recursion",
    "id_completeness_matrix_level": "step48_regression_gate_observed_dag_backdoor_frontdoor_zero_effect_formal_hedge_and_district_q_factor_cases_no_full_id_claim",
    "id_full_readiness_matrix_version": "id_full_readiness_matrix_v11_step80",
    "id_full_promotion_gate_version": "id_full_promotion_gate_v7_step94",
    "id_scoped_pearl_promotion_gate_version": "id_scoped_pearl_promotion_gate_v1_step87",
    "id_scoped_pearl_scope_manifest_version": "id_scoped_pearl_scope_manifest_v1_step88",
    "id_scoped_pearl_release_manifest_version": "id_scoped_pearl_release_manifest_v1_step89",
    "id_scoped_pearl_veto_runtime_attestation_version": "veto_pearl_scoped_runtime_attestation_v1_step90",
    "id_full_recursive_authority_coverage_version": "id_full_recursive_authority_coverage_v2_step86",
    "id_failure_certificate_coverage_version": "id_failure_certificate_coverage_v2_step84",
    "id_full_recursive_kernel_matrix_version": "id_full_recursive_kernel_v1_step91",
    "id_full_recursive_oracle_expansion_version": "id_full_recursive_oracle_expansion_v1_step92",
    "id_global_full_id_promotion_dry_run_version": "id_global_full_id_promotion_dry_run_v1_step93",
    "id_global_full_id_controlled_flip_version": "id_global_full_id_controlled_flip_v1_step94",
    "id_global_pearl_veto_runtime_attestation_version": "veto_pearl_global_runtime_attestation_v2_step96",
    "id_final_pearl_readiness_report_matrix_version": "id_final_pearl_readiness_report_v1_step97",
    "math_hypothesis_loop_readiness_matrix_version": "math_hypothesis_dialogue_loop_product_readiness_v1_step99",
    "id_authority_layer_level": "recursive_id_preferred_authority_with_backdoor_frontdoor_as_diagnostic_shortcuts",
    "recursive_subproblem_planner_implemented": 1,
    "recursive_subproblem_planner_level": "machine_readable_district_q_factor_subproblem_plan_no_new_authority",
}


def id_capability_flags() -> Dict[str, object]:
    return dict(ID_CAPABILITY_FLAGS)


__all__ = ["ID_ALGORITHM_STATUS", "ID_ALGORITHM_VERSION", "ID_CAPABILITY_FLAGS", "id_capability_flags"]
