from .engine_common import *
import numpy as np
import pandas as pd


class RowBuilderMixin:
    def _build_row(self, metrics: SourceMetrics) -> dict:
        cfg = self.cfg
        source = metrics.source
        human_statement = (
            f"Downside candidate '{metrics.action_name}' derived from observed relation '{source} -> {cfg.outcome_col}' may "
            f"decrease {cfg.outcome_col} over ~{metrics.lag} day(s); relation_strength={metrics.intervention_value:.2f}, "
            f"harm_risk={float(metrics.safety_scores['harm_risk_score']):.2f}, uncertainty={float(metrics.safety_scores['uncertainty_score']):.2f}. "
            f"Discovery is veto-oriented: validate in Level 3.2 before blocking."
        )
        dag_ann = metrics.dag_ann
        graph_fields = self._graph_link_fields("")
        local_dag_fields = self._local_causal_dag_fields(
            source=source,
            target=cfg.target_col,
            mediator_hint=metrics.mediator_hint,
            confounder_hint=metrics.confound_hint,
            graph_fields=graph_fields,
        )
        candidate_covariates = metrics.confound_hint or metrics.supporting
        post_treatment_columns = metrics.forbidden_adjustment_hint or metrics.mediator_hint
        source_role = self._infer_source_role(source, metrics.action_type, dag_ann=dag_ann)
        outcome_role = self._infer_outcome_role(cfg.target_col)
        edge_family = self._infer_edge_family(source_role, outcome_role)
        validation_design = self._infer_validation_design(source_role, outcome_role, candidate_covariates=candidate_covariates)
        preferred_estimand = self._infer_preferred_estimand(validation_design, cfg.target_col)
        outcome_kind = _as_str((self._outcome_profile or {}).get("kind", "continuous"))
        return {
            "insight_id": "",
            "source": source,
            "target": cfg.target_col,
            "lag": int(metrics.lag),
            "beta_k": float(metrics.corr),
            "delta_test": float(metrics.delta) if np.isfinite(metrics.delta) else np.nan,
            "strength": float(metrics.priority),
            "strength_semantics": "initial_alias_for_priority_score_before_selection",
            "recommendation": metrics.action_name,
            "human_statement": human_statement,
            "action_name": metrics.action_name,
            "action_type": metrics.action_type,
            "discovery_focus": "negative_actionable",
            "relation_sign_observed": int(metrics.relation_sign) if metrics.relation_sign != 0 else np.nan,
            "observed_relation_direction": "increase_target" if metrics.relation_sign > 0 else "decrease_target" if metrics.relation_sign < 0 else "unknown",
            "downside_action_reason": metrics.downside_mechanism,
            "source_family": _feature_family(source, self.cfg),
            "action_family": _action_family(metrics.action_name, self.cfg),
            "expected_direction_on_target": int(metrics.expected_direction_num) if metrics.expected_direction_num != 0 else np.nan,
            "expected_direction_label": metrics.expected_direction_label,
            "candidate_cause": source,
            "target_col": cfg.target_col,
            "treatment_col": source,
            "treatment_role": source_role,
            "source_role": source_role,
            "outcome_col": cfg.target_col,
            "outcome_role": outcome_role,
            "edge_family": edge_family,
            "validation_design": validation_design,
            "preferred_estimand": preferred_estimand,
            "outcome_kind": outcome_kind,
            "discovery_evidence_score": np.nan,
            "selection_score": np.nan,
            "discovery_support_sum": np.nan,
            "discovery_penalty_sum": np.nan,
            "discovery_support_votes": 0,
            "discovery_contradiction_votes": 0,
            "discovery_hard_red_flags": 0,
            "top_supporters": "",
            "top_penalties": "",
            "discovery_confidence_tier": "",
            "hypothesis_signal_score": np.nan,
            "hypothesis_signal_grade": "",
            "hypothesis_signal_reason_codes": "",
            "safety_risk_score": np.nan,
            "safety_risk_grade": "",
            "safety_risk_reason_codes": "",
            "safety_blocking": 0,
            "signal_safety_cell": "",
            "signal_safety_policy": "",
            "signal_safety_matrix_track": "",
            "signal_safety_blocking": 0,
            "signal_safety_reason_code": "",
            "signal_safety_matrix_version": 1,
            "mci_score": np.nan,
            "mci_val": np.nan,
            "mci_partial_corr": np.nan,
            "mci_t": np.nan,
            "mci_p_value": np.nan,
            "mci_pvalue": np.nan,
            "mci_q_value": np.nan,
            "mci_controls": "",
            "mci_source_parents": "",
            "mci_conditioning_set_y": "",
            "mci_conditioning_set_x": "",
            "mci_parents_y_count": 0,
            "mci_parents_x_count": 0,
            "mci_evaluated": 0,
            "mci_final_gate": 0,
            "mci_gate_reason": "not_evaluated",
            "mci_pass": 0,
            "candidate_covariates": candidate_covariates,
            "post_treatment_columns": post_treatment_columns,
            "mechanism_hint": _mechanism_hint(source, metrics.lag, metrics.corr),
            "supporting_features": metrics.supporting,
            "confounder_hint": metrics.confound_hint,
            "adjusted_confounders": "|".join(metrics.adjusted_confounders),
            "adjusted_corr": float(metrics.adjusted_corr) if np.isfinite(metrics.adjusted_corr) else np.nan,
            "adjusted_delta_test": float(metrics.adjusted_delta) if np.isfinite(metrics.adjusted_delta) else np.nan,
            "attenuation_after_adjustment": float(metrics.attenuation_ratio),
            "confounding_risk_score": float(metrics.confounding_risk_score),
            "adjusted_support_n": int(metrics.adjusted_support),
            # Discovery-only effect proxy. This is screening evidence, not an authorized causal estimate.
            "discovery_effect_proxy": float(metrics.causal_effect) if np.isfinite(metrics.causal_effect) else np.nan,
            "discovery_effect_proxy_std": float(metrics.causal_effect_std) if np.isfinite(metrics.causal_effect_std) else np.nan,
            "discovery_effect_proxy_ci_low": float(metrics.causal_effect_ci_low) if np.isfinite(metrics.causal_effect_ci_low) else np.nan,
            "discovery_effect_proxy_ci_high": float(metrics.causal_effect_ci_high) if np.isfinite(metrics.causal_effect_ci_high) else np.nan,
            "effect_proxy_semantics": "discovery_screening_proxy_not_causal_claim",
            # Legacy aliases retained for compatibility with historical outputs/tests.
            "causal_effect": float(metrics.causal_effect) if np.isfinite(metrics.causal_effect) else np.nan,
            "causal_effect_std": float(metrics.causal_effect_std) if np.isfinite(metrics.causal_effect_std) else np.nan,
            "causal_effect_ci_low": float(metrics.causal_effect_ci_low) if np.isfinite(metrics.causal_effect_ci_low) else np.nan,
            "causal_effect_ci_high": float(metrics.causal_effect_ci_high) if np.isfinite(metrics.causal_effect_ci_high) else np.nan,
            "effect_persistence_score": float(metrics.effect_persistence_score) if np.isfinite(metrics.effect_persistence_score) else np.nan,
            "ci_signal_score": float(metrics.ci_signal_score),
            "ci_raw_strength": float(metrics.ci_raw_strength),
            "ci_adjusted_strength": float(metrics.ci_adjusted_strength),
            "parent_competition_score": float(metrics.parent_competition_score),
            "parent_competition_pass": int(getattr(metrics, "parent_competition_pass", 0) or 0),
            "causal_screen_score": float(metrics.causal_screen_score),
            "incremental_r2": float(metrics.incremental_r2) if np.isfinite(metrics.incremental_r2) else np.nan,
            "conditional_beta": float(metrics.conditional_beta) if np.isfinite(metrics.conditional_beta) else np.nan,
            "conditional_beta_std": float(metrics.conditional_beta_std) if np.isfinite(metrics.conditional_beta_std) else np.nan,
            "conditional_t": float(metrics.conditional_t) if np.isfinite(metrics.conditional_t) else np.nan,
            "causal_screen_pass": int(metrics.causal_screen_pass),
            "residual_competition_score": float(metrics.residual_competition_score),
            "innovation_corr": float(metrics.innovation_corr),
            "innovation_beta_std": float(metrics.innovation_beta_std),
            "innovation_t": float(metrics.innovation_t),
            "innovation_pass": int(metrics.innovation_pass),
            "orientation_score": float(metrics.orientation_score),
            "orientation_dominance": float(metrics.orientation_dominance) if np.isfinite(metrics.orientation_dominance) else np.nan,
            "orientation_pass": int(metrics.orientation_pass),
            "mediator_hint": metrics.mediator_hint,
            "forbidden_adjustment_hint": metrics.forbidden_adjustment_hint,
            "dag_known": int(dag_ann.get("dag_known", 0)),
            "dag_node_type": _as_str(dag_ann.get("dag_node_type", "")),
            "dag_intervenable": int(dag_ann.get("dag_intervenable", 0)),
            "dag_action_name": _as_str(dag_ann.get("dag_action_name", "")),
            "dag_expected_direction": _as_str(dag_ann.get("dag_expected_direction", "")),
            "dag_risk_paths": _as_str(dag_ann.get("dag_risk_paths", "")),
            "dag_review_flag": int(dag_ann.get("dag_review_flag", 0)),
            "actionability_class": (
                "mapped_action_candidate"
                if int(dag_ann.get("dag_known", 0)) == 1 and int(dag_ann.get("dag_intervenable", 0)) == 1
                else "actionable_but_unmapped" if int(dag_ann.get("dag_known", 0)) != 1 else "structural_warning_candidate"
            ),
            "risk_flags": "|".join(sorted(set(metrics.risk_flags))),
            "causal_plausibility_score": float(metrics.causal_plausibility),
            "intervention_value_score": float(metrics.intervention_value),
            "downside_action_score": float(metrics.downside_action_score),
            "validation_readiness_score": float(metrics.validation_readiness),
            "testability_score": float(metrics.testability_score),
            "benefit_score": float(metrics.safety_scores["benefit_score"]),
            "harm_risk_score": float(metrics.safety_scores["harm_risk_score"]),
            "uncertainty_score": float(metrics.safety_scores["uncertainty_score"]),
            "safety_net_score": float(metrics.safety_scores["safety_net_score"]),
            "safety_precheck": metrics.safety_precheck,
            "structural_risk_score": float(metrics.structural_risk_score),
            "priority_score": float(metrics.priority),
            "reason_codes": "|".join(sorted(set(metrics.reason_codes))),
            "exclusion_reasons": "|".join(sorted(set(metrics.exclusion_reasons))),
            "coverage": float(metrics.test_meta["coverage"]),
            "timestamp_ok": float(metrics.test_meta["timestamp_ok"]),
            "action_defined": float(metrics.test_meta["action_defined"]),
            "window_ok": float(metrics.test_meta["window_ok"]),
            "covariate_support": float(metrics.test_meta["covariate_support"]),
            "actionability_score": float(metrics.test_meta["actionability"]),
            "rolling_stability": float(metrics.stability) if np.isfinite(metrics.stability) else np.nan,
            "stability_windows": int(metrics.stability_windows),
            "lag0_corr": float(metrics.lag_meta["lag0_corr"]) if np.isfinite(metrics.lag_meta["lag0_corr"]) else np.nan,
            "future_corr": float(metrics.lag_meta["future_corr"]) if np.isfinite(metrics.lag_meta["future_corr"]) else np.nan,
            "lead_corr": float(metrics.lag_meta["past_corr"]) if np.isfinite(metrics.lag_meta["past_corr"]) else np.nan,
            "leakage_score": float(metrics.lag_meta["leakage_score"]),
            "regime_shift_score": float(metrics.regime["regime_shift_score"]) if np.isfinite(metrics.regime["regime_shift_score"]) else np.nan,
            "regime_alignment_score": float(metrics.regime["regime_alignment_score"]) if np.isfinite(metrics.regime["regime_alignment_score"]) else np.nan,
            "recent_corr": float(metrics.regime["recent_corr"]) if np.isfinite(metrics.regime["recent_corr"]) else np.nan,
            "past_corr": float(metrics.regime["past_corr"]) if np.isfinite(metrics.regime["past_corr"]) else np.nan,
            "recommended_window_days": int(metrics.design["recommended_window_days"]),
            "recommended_dose": metrics.design["recommended_dose"],
            "min_trials_recommended": int(metrics.design["min_trials_recommended"]),
            "trial_design_hint": metrics.design["trial_design_hint"],
            "primary_metric": metrics.design["primary_metric"],
            "safety_metrics": metrics.safety_scores["safety_metrics"],
            "candidate_stratum": "",
            "candidate_stratum_rationale": "",
            "candidate_stratum_confidence": "none",
            **graph_fields,
            **local_dag_fields,
            "alternative_explanations": "",
            "alternative_explanations_tier": "low",
            "proposal_stage": "causal_proposal_prepolicy_layer",
            "causal_interpretation_level": "proposal_only",
            "veto_candidate": 1,
        }
